### ISSUE TITLE
Detect eyes, nose and mouth precisely.

### ISSUE THREAD

**Issue by jointdev** [jeeliz/jeelizFaceFilter#1]
Congratulations for this incredible library!

Can I get precise coordinates of eyes, mouth and nose? 

Let me explain what I want to do ... I'm not a blander/threeJs professional and I want to use CSS3 capabilities to position objects on camera using coordinates delivery from jellizFaceFilter library. This is possible?

**Comment by xavierjs** [comment]
Hello,

Thank you for your interest about JeelizFaceFilter API :)
Unfortunately the detection of the face is a global detection. We do not detect specific keypoints like BRFv4 for example (https://github.com/Tastenkunst/brfv4_javascript_examples).

We are going to release an upgrade where the mouth opening coefficient is detected.

But the current head detection frame is centered on the middle of the eyes so you can retrieve the position of the eyes quite accurately. Idem for the nose. But for the mouth I think there will be more variability because there are people with a lot of space between the mouth and the nose, and other whose mouth is almost stitched to the nose.

I will put the dev of a demonstration using canvas2D or CSS3 on my pipeline and keep you informed.

**Comment by jointdev** [comment]
Great! I already tested the brfv4 library before but I prefer your solution, including I can't use the brfv4 in a commercial app and the licence is expensive (in brazilian currency).

I'm following the "luffys hat" tutorial that is a perfect start point for my project.

I will share my project in github when I finish him.

Thank you very much.

**Comment by xavierjs** [comment]
Hi,
We have add the CSS3D support for easier integration.
The link to the boilerplate and another CSS3D example are included from the README.
I tested it on Ipad, on android and desktop.

**Comment by jointdev** [comment]
Great! Thank you very much!

This solution definitely solved my problem, now I'm trying to take a picture and bring the comedy-glasses togheter, I'm seriously considering use fabricJS for that, once I need to manipulate the image inside canvas, I don't know if this is the correct way ...

**Comment by nitish24p** [comment]
Is it possible to only color certain parts of the face, like the eyes or the lips and then the colored portion moves as the person smiles etc

**Comment by xavierjs** [comment]
this is not possible bc the detection is global
