### ISSUE TITLE
Rear facing camera feature

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizFaceFilter#10]
Hi all,
Is there any chance you'll be adding a rear-facing camera option in the not-too-distant future? I've seen other webAR executions of this option (for example - https://www.vertebrae.com/mobile-web-ar-advertising/#more-2644).
Again, love what you've been doing and look forward to what's next!

**Comment by xavierjs** [comment]
Hi Andrew,

It won't be a big deal.
We prefer to include the capture of the webcam video feed in the library because we have put a lot of polyfills and tests in order to make it work everywhere (many other face detection libraries keep it outside).

I am working on adding a faceSwap demo in the repository to illustrate multi face detection, then I will add the rear-facing camera option (at the beginning of next week). I think I will  add an initialization option to provide custom getUserMedia constraint which will override the application constraints and add a method to get the different media devices.

**Comment by MerovingianByte** [comment]
Hello @bjlaa and @xavierjs , is there an email I can use to contact you? Thanks.

**Comment by andrewdeutsch** [comment]
Great! I don't think I was specific enough though. The example I sent you claims to provide plane detection. That wouldn't be possible yet in standard browsers yet, correct?

**Comment by xavierjs** [comment]
Hi Andrew,
I have improved the videoSettings init parameter and updated the readme.
We can tweak the camera facingMode now.

I think for AR, the plane detection will be taken into account on browser side, because it also depends on other data coming from accelerometers or 3D scanners.
Currently there is webARCore. I think we can get the raw webcam video element. I have also added the possibility to use a custom <video> element instead of using our webcam requester. There is a demo here: [https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/](https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/)

But I think that WebARCore will be replaced by WebXR. The standard is currently too young and I think there will be breaking upgrades, so we still wait before working with it.

**Comment by andrewdeutsch** [comment]
This is great. Thanks, Xavier.

**Comment by chrispoole102** [comment]
Hello @xavierjs,

I looked over this issue and attempted to implement it in my project. Unfortunately I can't seem to get the video settings to apply. I'm confident my browser / device combo supports rear-facing camera with these settings because I've been messing around with other face tracking sdks and I managed to implement it with those. I'd much prefer to use yours, though, so how do I solve this? Has there been an update since this issue was resolved that might have broken it again? I'm aware that at some point getUserMedia was updated, but I'm not sure about the details.

Thanks,
-Chris

**Comment by xavierjs** [comment]
Hi,

You need to give specific `videoSettings` ( see https://github.com/jeeliz/jeelizFaceFilter#optionnal-init-arguments ) when calling `JEEFACEFILTERAPI.init(...)` method. Typically:
```
JEEFACEFILTERAPI.init({
  videoSettings: {facingMode: 'environment'}
})
```

Best,
Xavier
