### ISSUE TITLE
glasses movement

### ISSUE THREAD

**Issue by Luigixx89** [jeeliz/jeelizFaceFilter#100]
Hello, sorry for my english.
Sorry if possible reduce or remove the game that has the glasses when the face is moved?

increase eye movement sensitivity

when the head moves a few degrees, the glasses remain still

Is it possible to glue the glasses on the face and make it move exactly as the head moves?

eugual canvas in website ray-ban.com
look and prend try sunglasses
https://www.ray-ban.com/italy/occhiali-da-sole/RB3025%20UNISEX%20043-aviator%20classic-oro/805289602057

I hope you can help me. Thank you

**Comment by xavierjs** [comment]
Hi,

It is possible, we can offer this kind of development services. We have a dedicated version of FaceFilter for sunglasses (used in https://jeeliz.com/sunglassses).
You can contact our commercial service at contact__at__jeeliz.com for more information.

I close the issue since it is not linked to a specific problem with this library.

Best,
Xavier

**Comment by Luigixx89** [comment]
ok thanks...
This link http://contact__at__jeeliz.com/ not work

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 20 mag 2019 alle ore 20:36 Bourry Xavier <
notifications@github.com> ha scritto:

**Comment by xavierjs** [comment]
Hi,

This is an email address, you just need to replace the __a__ by @

Best,
Xavier
