### ISSUE TITLE
Emotion/expression detection 

### ISSUE THREAD

**Issue by sliktrik** [jeeliz/jeelizFaceFilter#104]
would it be possible with jeeliz to detect anger, happiness, disgust etc?

**Comment by hadrichouki** [comment]
Sûre 

Chouki Hadri
Envoyé de mon iPhone

**Comment by sliktrik** [comment]
Any suggestions on how to achieve this?

**Comment by xavierjs** [comment]
Hi,

First you have to use https://github.com/jeeliz/jeelizWeboji instead of FaceFilter.
So that you get 11 face morph coefficients.
Then you have to bind the face morph coefficients to the emotions.
The easiest way is a linear association. For each expression you associate a weight to the expression detection. Then you apply a threshold and you choose the expression which has the higher score.

Best,
Xavier

**Comment by xavierjs** [comment]
In this issue, @abhilash26 propose a solution based on Jeeliz Weboji to detect high level face expressions: https://github.com/jeeliz/jeelizWeboji/issues/25#issuecomment-526015842
