### ISSUE TITLE
Face detection using IP camera

### ISSUE THREAD

**Issue by vijaysagi1** [jeeliz/jeelizFaceFilter#11]
**Is your feature request related to a problem? Please describe.**
We have surveillance IP camera to detect faces from 10-20m distance. we want to detect faces at low lighting conditions using javascript framework.

**Describe the solution you'd like**
We use dlib for face recognition (using python framework). Using detected faces from jeeliz framework and process it using python framework.

**Describe alternatives you've considered**
we  tried using haarcascade.xml for face recognition it is detecting  non-faces as faces and the image quality is very low.

Pls suggest how can we use your js framework along with python framework.

**Comment by xavierjs** [comment]
Hello,

Thank you for your interest for our library

Our framework requires an access to the GPU, it cannot run on standard server side.

We make it run on server side to provide an image fallback for https://jeeliz.com/sunglasses with these tricks: 
- the server runs with ubuntu 16.04 with a blackbox window environment (quite minimalist)
- we use slimerjs with node.js, which is a headless browser. Unlike phantom.js, it supports WebGL and it is based on firefox. It has the same interface than phantom.js.
But this is only to process images, and there is a problem because slimerjs seems not maintained and it does not work with the last firefox versions (above FF57 since they changed the rendering engine), so we have to use FF52.

I think if you want to do things simply, you have to get the video stream in the web browser, inside a <video> element (not a flash video or other fancy plugin and to process it fully client side. I see 2 solutions:
- maybe you can stream the video image of the webcam into a <video> element using mediaStream API and then process it with our API. We can then add a tweak to disable the user direct webcam request, it will be quick to implement :) ,
- or you can use a standard USB webcam and use it as a wireless webcam with usb2air : https://www.amazon.com/HuddleCamHD-HC-USB2-AIR-Wireless-Extender-Bandwidth/dp/B073RSW19H

**Comment by xavierjs** [comment]
Hi,

I have added the possibility to detect faces on custom <video> elements. There is a demo here (included in the repo) where the faces is detected from a MP4 video file:
[https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/](https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/)

I think if you manage to stream the video from your IP camera to a <video> element (you can take a look here : https://www.wowza.com/community/questions/2442/how-to-re-stream-video-from-an-ip-camera-to-html-5.html ) then you will be able to use our lib.

I am interested by your feedbacks !

Cheers,
Xavier

**Comment by xavierjs** [comment]
Hi @vijaysagi1 

Have you managed to use this lib for you problem ? Have you tried the solutions I have suggested above ?

**Comment by xavierjs** [comment]
No news -> I close the issue. If you have the same problem feel free to re-open the issue.
