### ISSUE TITLE
Multiple faces detection - Delay on another faces detection

### ISSUE THREAD

**Issue by jointdev** [jeeliz/jeelizFaceFilter#12]
Hello people, I'am facing a strange problem with multiple faces detection. After detect first face, the API take a longer time to detect the secound face, and sometimes detect only the secound face and ignore the first face.

I don't know if I'm doing something wrong, there's no diference from my code and the demos, except the fact that I'm using plane geometry and loading .png images instead of 3d models.

`    var threeStuffs = THREE.JeelizHelper.init(spec, SETTINGS.maxFaces, detect_callback);

    //Carrego o primeiro sticker
    geometry = new THREE.PlaneGeometry(1,1,1);
    material = new THREE.MeshBasicMaterial({
        map : THREE.ImageUtils.loadTexture('assets/stickers/sticker1.png'),
        transparent: true,
        //color: 0x0000ff, 
        side: THREE.DoubleSide
    });

    plane = new THREE.Mesh(geometry, material);
    plane.scale.set(3,3,3);
    plane.position.set(0.0, 1.1, 0.0);
    plane.frustumCulled = false;

    threeStuffs.faceObjects.forEach(function(faceObject) {
        faceObject.add(plane.clone());
    });

    //CREATE THE CAMERA
    var aspecRatio=spec.canvasElement.width / spec.canvasElement.height;
    THREECAMERA=new THREE.PerspectiveCamera(SETTINGS.cameraFOV, aspecRatio, 0.1, 100);`

Thank you very much!!!

**Comment by xavierjs** [comment]
Hello,

Your code is nice, there should be no problem, we will investigate.
The multiple face detection feature is quite new so I think there are still some bugs.

It is normal that it takes longer time to detect the second face because at the beginning the whole computing power is used for detecting the first face, then we process less new detection trials to focus on the first face tracking. Then for the 3rd or 4th face for example the computing power for searching is still the same so it should not take longer than to detect the second face but the tracking may be a bit less accurate (because we have to split it between the faces to track).

But the second problem is not normal, I think we have a bug at the unstitching procedure (when 2 detection frames are too close, we detect that it is the same face and we unstitch the one which is the most recently detected).

**Comment by xavierjs** [comment]
Hi Lucas,

I have found a big issue with multiple faces detection which affected the stability.
I have pushed the correction on the repository, I hope it will work better for you now.

**Comment by jointdev** [comment]
Greeeaat Xavier! Is working perfectly now! Thank you very much!

![image](https://user-images.githubusercontent.com/13009321/40694487-2509a154-6393-11e8-8d69-1376d46e9720.png)
