### ISSUE TITLE
using the api with vue js

### ISSUE THREAD

**Issue by dbebli** [jeeliz/jeelizFaceFilter#138]
**Describe the bug**
Hello, I encouter many problems while trying to use the api

first I tried the npm package and use it like this 
const faceFilter = require('facefilter')
I was unable to access size_canvas method and in the init function it returns this error 
Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at eval (jeelizFaceFilterES6.js?4c01:134)

then i cloned the github repo and tried to use it like this 
const faceFilter = require(mypath/jeelizFaceFilter)
here I dont have access to any methods
I tried the es6
require(mypath/jeelizFaceFilterES6)
and I got this

jeelizFaceFilterES6.js?17a5:151 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.eval (jeelizFaceFilterES6.js?17a5:151)
    at eval (jeelizFaceFilterES6.js:3980)
    at Module../src/lib/jeelizFaceFilter/dist/jeelizFaceFilterES6.js (app.js:2950)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (Home.vue?76f2:28)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/Home.vue?vue&type=script&lang=js& (app.js:932)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (Home.vue?e0fd:1)

I lost a lot of time trying to figure out how to use this API can someone help please ?

**Comment by xavierjs** [comment]
Hi,
I don't use vue.js

**Comment by dbebli** [comment]
@xavierjs dont you recognize those errors at least ?

**Comment by Dailyscat** [comment]
me too 
in my case 

I used react and imported this package using git+https://git@github.com/jeeliz/jeelizFaceFilter.git
.
But during the initial process, there was an error in the parse (z) inside the jeelizFaceFilterES6.js.
It wasn't json, it was because the html string was in it. I couldn't fix the source, so I was looking for an error solution.

**Comment by xavierjs** [comment]
Hi,

I have added a section into the README.md about use of bundlers like webpack: https://github.com/jeeliz/jeelizFaceFilter#with-a-bundler

I think the library is trying to load NNC.json using AJAX, and since you use webpack instead of a classical HTTP static server, it will get a document containing an error in HTML format instead of the JSON file.

In this case, this error should be clear in the NETWORK tab of the browser web console, you should first see an XMLHttpRequest asking for NNC.json, and see that the response is not a JSON file.

I wish it will help.

**Comment by dbebli** [comment]
@Dailyscat make sure the path to your nnc file is correct. I checked the response from hte NNC file and it wasn't json so i figure that the path to the my file wasnt correct. 
though I couldnt get the real path of my file so i just put it along with the index.html (which is the entry point of the vue project) file in the public folder

**Comment by dbebli** [comment]
@xavierjs I dont know If you were talking to me but I was able to fix the problem yesterday
I should have close the issue sooner. Thank you for the answer though. The API is pretty cool !

**Comment by dineshBD** [comment]
hey @dbebli so great to see you could fix the problem. I am trying to use the ES6 version in react but I am unable to do it correctly. Can you explain what changes you made? Thanks
