### ISSUE TITLE
iOS 13 / Android v9 camera resolution flipped and causes zoom-in effect

### ISSUE THREAD

**Issue by ThorstenBux** [jeeliz/jeelizFaceFilter#144]
**Describe the bug**
On iOS 13 it seems like Safari automatically flips cameraWidth and cameraHeight if the camera is opened in portrait mode. Because JeelizResizer is doing a flip as well this causes a double flip and due to that a wrong camera resolution. Which leads to a zoom-in effect.

**To Reproduce**
1. Start Jeeliz with a Resizer
```
  startJeeliz() {
    window.JeelizResizer.size_canvas({
      canvasId,
      isFullScreen : true,
      callback     : (isError, videoSettings) => {
        this.initFaceFilter(videoSettings)
      },
      onResize: () => {
        if (threeCamera) {
          threeCamera.aspect = CANVAS.width / CANVAS.height
          threeCamera.updateProjectionMatrix()
        }
      }
    })
  }
```
2. Pass the video parameters to init
```
  initFaceFilter(videoSettings) {
    console.log('VideoSettings', videoSettings)
    window.JEEFACEFILTERAPI.init({
      canvasId,
      videoSettings,
```
3. Run the app and open the camera stream
4. See that the video appears to be zoomed in

**Expected behavior**
Camera is opened with correct resolution

**Desktop (please complete the following information):**
 - OS: iOS 13
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS13
 - Browser Safari

**Comment by xavierjs** [comment]
Hi,

`JeelizResizer` is provided by this helper:
https://github.com/jeeliz/jeelizFaceFilter/blob/master/helpers/JeelizResizer.js

The goal is to ask for a camera resolution which is the closest as possible to the canvas resolution. Indeed,
- if the camera resolution is too high compared to the canvas resolution, we will loose time in refreshing a heavy video texture,
- if the camera resolution is too low compared to the canvas resolution, it will look crapy, blurry or pixelized,
- if the aspect ratio are too different, there will be large cropped areas.

If `isFullScreen` is `true` like in your example it should set `canvas.width` and `height` to the dimensions of the screen (so 1920 x 1080 pixels).

Then because it is in portrait mode, all the resolutions:
```
  const _cameraResolutions = [ //all resolutions should be in landscape mode
    [640,480],
    [768,480],
    [800,600],
    [960,640],
    [960,720],
    [1024,768],
    [1280,720],
```
Will be reversed.
So we should require a video of 720 pixels width and 1280 pixels height.
I will update the helper to add the fullHD resolution and to log the ideal resolution.

**Comment by xavierjs** [comment]
Oh I have understood. I have found discussions about this topic and they have implemented an incorrect behavior :( . I will add a workaround tomorrow.

**Comment by xavierjs** [comment]
Hi @ThorstenBux 
I have pushed a workaround for IOS13.
I hope it will fix your bug.

**Comment by ThorstenBux** [comment]
Testing it now

**Comment by ThorstenBux** [comment]
Works for me. Thanks @xavierjs

**Comment by FIABTom** [comment]
@ThorstenBux , which minor version of IOS13 are you using? 

I'm finding that on my devices running 13.1.3 this workaround is infact causing an issue now. I'm wandering if Apple have since fixed the problem? 

I've got around this by removing this workaround, and ignoring the device orientation check and just looking at screen sizes in the `is_portrait` function.

```
is_portrait: function(){
     return (window['innerHeight'] > window['innerWidth']);
},
```

**Comment by xavierjs** [comment]
Hi,

Thank you for your feedback @FIABTom 
I will disable the workaround for IOS 13.1.3+

**Comment by xavierjs** [comment]
@FIABTom Can you test the latest commit? It should disable the workaround with IOS 13.1.3+
Thanx

**Comment by ThorstenBux** [comment]
@xavierjs we can reproduce this issue on Android as well. Judging from your code changes you only fixed it for iOS 12+, right? Reopening and updating the header to track it for Android too

**Comment by xavierjs** [comment]
Hi @ThorstenBux 
I will add the workaround for Android9. 
But I think we will have to wait 6 months to allow browser makers to talk a bit how should be the default behavior, then another 6 months for Apple to implement it =)

**Comment by ThorstenBux** [comment]
I'm actually wondering if the video stream should always be opened in landscape and portrait is handled by the device. Because on iOS12 it is the same issue I just didn't notice when I started to write my app.

**Comment by xavierjs** [comment]
@ThorstenBux  You mean we should give the video stream as landscape for IOS 12+ ?

**Comment by xavierjs** [comment]
Hi @ThorstenBux Do you have more information about this issue?
Thank you,
Xavier

**Comment by ThorstenBux** [comment]
From what I can see is that the issue is present on iOS 12+ and Android 9+ (but didn't test on earlier Android versions) We fixed it by flipping whatever comes from the resizer during initialization of JeelizAPI
```
  initFaceFilter(videoSettings) {
    window.JEEFACEFILTERAPI.init({
      canvasId,
      videoSettings: Object.assign(videoSettings, {
        flipX       : true,
        idealWidth  : videoSettings.idealHeight,
        idealHeight : videoSettings.idealWidth,
      }),
```
As we are only targeting mobile that works for us.

**Comment by xavierjs** [comment]
Hi @ThorstenBux 
Thank you for this information.
I will commit the fix now, even if I think that it is not a very intuitive behavior .
