### ISSUE TITLE
Loading module & helpers in code stack instead of manually importing in HTML

### ISSUE THREAD

**Issue by jackbsv** [jeeliz/jeelizFaceFilter#185]
Instead of loading in all the scripts manually in the `html` file, it would be good to load them into the code stack using the `import` method. This is possible as I've run a few tests and it works great for what we are using it for.

Each script would require an `export` instead of `JEEFACEFILTERAPI.<function name>` in order to work.

I can raise a PR for this no problem, just wondering if you're open to the idea?

**Comment by xavierjs** [comment]
Hi @jackbsv 

Thank you very much for your proposal.
Currently, JavaScript `import` is still a bit too young IMHO to be used in production ( https://caniuse.com/#search=import ). It depends on the context. For a webapp targeting the Chinese market it can be a problem since UC-Browser is very popular there.

But for sure it is interesting to provide examples using `import` here.

The demo using `import` is the ES6 boilerplate, here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/cubeES6
But the helpers are not imported using `import`. You can submit a pull request to improve this demo to only use `import` statements. Feel free to add explanations in the main README or to create a specific README in the demos/threejs/cubeES6
You can also change the suffix (from ES6 to other stuff).

The main script created to be imported is `dist/jeelizFaceFilter.module.js` . It is the same than `jeelizFaceFilter.js ` except that it has an export statement.

I will push in 10 minutes a code to add export statement for the helpers

**Comment by xavierjs** [comment]
I have improved the ES6 demo, but it is not perfect, I am not a specialist in that area (variants of JS like CommonJS, ES6, ...).
Feel free to add your contribution.

**Comment by jackbsv** [comment]
Okay will do :)

**Comment by jackbsv** [comment]
Hey @xavierjs ,

I've got things up and running now so all should be good. My only concern is that the main API script `jeelizFaceFilter.js` seems to already compiled and minified and there's no sign of the source code anywhere in this repo. This creates a small issue as we can't do much with a compiled code set. So, for now, the main API can live in its own namespace of `JEEFACEFILTERAPI` but the helpers are going to live in a separate namespace. Hope this is okay. I'll try and make the PR now :)

**Comment by jackbsv** [comment]
Hey @xavierjs , Have you been able to check this out yet?

**Comment by xavierjs** [comment]
Hi @jackbsv 

Thank you for your work.
But currently I don't want to replace the main code by ES6 one.
The main reason is that I want to keep the library as framework agnostic as possible (NPM, webpack introduce new specificities).

I have 3 proposals:
- You can submit a PR for ES6 compatibility, but I would like that to put ES6 stuffs in a separate directory (like package.json, webpack.config.js, ...) and to find a solution to have helpers usable both in ES6 and ES5 (if we replace `var` by  `export const` it does not work. That's why I put `try { module.exports = <module_name>; }` at the end of the helpers.).
- You can be the official ES6 repository of the library, put a link from the README.md of this repository. 
- We can maintain 2 branches of this repository

What do you think? 
Best,
Xavier

**Comment by xavierjs** [comment]
Hi @jackbsv 

I have added a NPM/React/Three-Fiber boilerplate to the repository: https://github.com/jeeliz/jeelizFaceFilter/tree/master/reactThreeFiberDemo

It uses facefilter NPM module (which has been revamped too) and a specific helper.
