### ISSUE TITLE
Can I get face recognition speed up?

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#20]
I did research jeelizFaceFilter and jeelizGlassesVTOWidget. Also I did develop web application with jeelizFaceFilter. Because jeelizGlassesVTOWidget library is minified. 

But jeelizFaceFilter is slower than jeelizGlassesVTOWidget in face recognition. How can I do it faster like jeelizGlassesVTOWidget in face recognition?

[IMG_4472.MOV.zip](https://github.com/jeeliz/jeelizFaceFilter/files/2204520/IMG_4472.MOV.zip)

I uploaded video. 
thanks for jeeliz developer

**Comment by xavierjs** [comment]
Hi,

The answer is in part in this issue of the VTO widget : https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2

We are still working on improving the speed of FaceFilter but it won't be as fast as the VTO widget since the 3D engine is less optimized and it is not a 100% GPU workflow.

Some speed improvements are still coming for the next versions.

Cheers,
Xavier

**Comment by whilemouse** [comment]
It was good answer. 

Cheers too.

**Comment by xavierjs** [comment]
Hi,

I have pushed big improvements (faster neural net, lighter version of the neural net, ++ responsive).
I wish it will speed up your app !

Cheers,
Xavier

**Comment by whilemouse** [comment]
unbelievable. It's very fast like jeelizVTO. I love it.
thanks xavierjs.
