### ISSUE TITLE
Inverted image with new jeelizFaceFilter.js

### ISSUE THREAD

**Issue by rishabh-sonal** [jeeliz/jeelizFaceFilter#200]
If you are submitting a bug report, please provide:

* I am using the jeelizFaceFilterjs along with NN_DEFAULT.json with my local code. The image that i am getting in canvas is inverted. 
* you can reproduce the same issue on your demo: https://jeeliz.com/demos/faceFilter/demos/threejs/werewolf/
 here you will see the image is coming upside down.
* Right now I am using css to fix it from my side, but would like to see it fixed from the jeeliz itself.
* Also the image in the canvas looks a bit elongated. You could replicate this too on the https://jeeliz.com/demos/faceFilter/demos/threejs/werewolf/

**Comment by xavierjs** [comment]
Hi,

This bug has been fixed in the latest commit ( https://github.com/jeeliz/jeelizFaceFilter/commit/bf6bfafb6f1e4effd59b596068886ec1f6e56a03 )
`videoTransformMat2` needs to be applied to video texture coordinates to handle video orientation and stretching.
I have updated https://jeeliz.com/demos/faceFilter/demos/threejs/werewolf/
