### ISSUE TITLE
Issues in including external model(except that from listed in NN) to JeelizFaceFilterAPI

### ISSUE THREAD

**Issue by nandu19981998** [jeeliz/jeelizFaceFilter#207]
Hi,

I'm currently working with a web based application that enables virtual TryON, mainly composed of superimposing 3D objects to earpoints in face.
I was successful in using NN_default.json model to extract the neckpoints, but I like to have earpoints as well.

Is there any way in which I could include the model that I have developed that identifies both earpoints and neckpoints to the JeelizFaceFilterAPI.

Thanks in advance!!!

**Comment by xavierjs** [comment]
Hi,

We use a proprietary file format for the neural network model since I use my own toolchain to create and train neural networks (I don't use TF or Torch or Keras).
Moreover, this library does not extract the face landmarks positions before computing the pose; but directly get the pose from neural network output.
The pose is computed to be aligned with a virtual point between the 2 eyes and scaled according to the distance between the 2 ears. The neck is near the pose central point so you can compute the neckpoints as you do with current output data quite accurately. but ears are too far to get accurate positioning.

I have another library called WebAR.rocks.face which outputs face landmark position. Different NN models are provided and demos, including earrings virtual try-on. I charge for it ( less than my competitors and there is no cost per user session ). You can contact me at contact__at__webar.rocks if you are interested.

**Comment by nandu19981998** [comment]
Thanks for your reply, will look into it and get back to you
