### ISSUE TITLE
Face replacement demo not working with custom image

### ISSUE THREAD

**Issue by gebeer** [jeeliz/jeelizFaceFilter#210]
The demo at https://jeeliz.com/demos/faceFilter/demos/faceReplacement/image/ is not working correctly with custom images.

After choosing a custom image, the canvas shows a still image of the camera capture with a blue frame.
![ 2021-01-23-13:48:49](https://user-images.githubusercontent.com/3088950/105578632-e3dce100-5d81-11eb-93b6-b7f2e0b7830f.png)

It seems like the build_artPaintingMask() function is not working correctly. It should create a hidden canvas with the uploaded image, detect the face and log the detected State coordinates in the console. all of this is not happening. Instead the callbackTrack() function is being called in an endless loop.

**Comment by xavierjs** [comment]
Hi buddy it should work now

**Comment by ianmichaelxp** [comment]
How can i improve the tracking of the face of the custom image? Because it is being tracked to random points, as shown in the screenshot.
![Captura de tela de 2021-01-26 15-26-28](https://user-images.githubusercontent.com/37078140/105888176-6916fe80-5feb-11eb-8a5c-d86efe99f7a0.png)
![Captura de tela de 2021-01-26 15-26-53](https://user-images.githubusercontent.com/37078140/105888179-69af9500-5feb-11eb-9574-94b1b59fbeeb.png)

**Comment by xavierjs** [comment]
There was a bug in the core (the texture set by `set_inputTexture` was Y-flipped). I have also increased the detection threshold a bit.
