### ISSUE TITLE
Can I do web cam control?

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#22]
I tried search <video> element. but It's in jeelizFaceFilter.js(minified).
I want cam size adjustment.

**Comment by xavierjs** [comment]
I don't understand what you are looking for. You want to change the webcam resolution ?

**Comment by whilemouse** [comment]
sorry. I missed video element.
Yes. I want change webcam resolution.

**Comment by xavierjs** [comment]
It is explained here : https://github.com/jeeliz/jeelizFaceFilter#optionnal-init-arguments

**Comment by whilemouse** [comment]
I want to change webcam distance.
ex) galuxy8s's webcam distance have to the same  iPhone6s's webcam distance.
I tried change webcam resolution in idealWidth, idealHeight. But it can only resolution. 
How to change webcam distance

![galuxy8s](https://user-images.githubusercontent.com/16111790/43118007-ba503c36-8f4a-11e8-9d2e-3933ef2eac7d.jpg)
![iphone6s](https://user-images.githubusercontent.com/16111790/43118008-ba7cec0e-8f4a-11e8-8eec-0b197ce039e3.jpeg)

**Comment by tetreault** [comment]
I don't believe you can update "distance". Here's the [media streams constraints](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints) for your reference @whilemouse

**Comment by xavierjs** [comment]
Hi,

The zoom effect is due to camera Field of View or zoom which is different from one camera to another.
With Linux/Ubuntu you can tweak manually the webcam settings by launching v4l2ctrl in the console.
The resolution will change nothing.

We have put the getUserMedia module into the lib because there are a lot of workarounds and polyfill to make it work on all configurations. But you can also provide your own video element (from webRTC or a static video file) like in this demo : https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/

The lib only crops either height/bottom (if the video is more portrait than the canvas) or left/right borders (it the video is more landscape than the canvas) to fit the video element into the canvas.

It would be great to add additionnal camera settings in the media streams constraints or the getUserMediaAPI like zoom control, manual aperture, access to the FOV...
