### ISSUE TITLE
Callback track not working when switch to another tab

### ISSUE THREAD

**Issue by tuanna2** [jeeliz/jeelizFaceFilter#221]
I am building a video call application with jeelizFaceFilter
But can't show video when I switching to another tab because track not working callback, when I switch it back on it works normally again.
How to detect video when not in current tab??

**Comment by tuanna2** [comment]
Currently, my app does not have audio when calling each other
Is there a way to include audio while streaming?

**Comment by xavierjs** [comment]
Hi,

I have added an init option to do the job - see the last item of https://github.com/jeeliz/jeelizFaceFilter#optional-init-arguments
The option is `isKeepRunningOnWinFocusLost` and is toggled off (`false`) by default.
Warning: This property should be given to `JEEFACEFILTERAPI`, not the helper:

```
  JEEFACEFILTERAPI.init({
    isKeepRunningOnWinFocusLost: true,
   .... other properties and stuffs
```

I have tested it with Chrome.

**Comment by tuanna2** [comment]
Hi @xavierjs 
Thank you for the addition of this feature.
But I feel when I turn this option on, my device is quite slow and laggy.
The console also displays this warning a lot

`performance warning: READ-usage buffer was written, then fenced, but written again before being read back. This discarded the shadow copy that was created to accelerate readback. ﻿`

Hope you can further improve the performance for this feature.
Thank you very much!!

**Comment by xavierjs** [comment]
Hi @tuanna2 
Thank you for your feedback.
The rendering is slowed down when the tab is switched for 3 reasons:

* The tab has lost priority, so Javascript is slower
* The `readPixel()` is not asynchronous anymore, otherwise it would stall when the tab is not active. The warning you get is normal, it is when we switch from asynchronous to synchronous `readPixels`. Then we discard the last reading.
* We add a 50 millisecond timeout to ensure rendering is finished and to not take too much computing resources, otherwise the browser may discard the whole WebGL context.

When the tab become active again, it may take a few seconds before re-adjusting the number of face tracks per seoond.
With Chrome, the tab is considered as active either at the first loading, or when the tab is switched off, then switch on and clicked on (the `window.onfocus event` should be fired)
