### ISSUE TITLE
Access to public api through functions

### ISSUE THREAD

**Issue by MateuszKicinski** [jeeliz/jeelizFaceFilter#24]
When using facefilter through npm I realized that it is not convenient to import and use the library in my project which is made up of many modules and components. To access the api I need to reference window element like this:
`window['JEEFACEFILTERAPI']`
which is not really an elegant solution 

In my opinion it would be much better if the lib would export function which can be utilized within other scripts so it can be accesed like that:
```
import facefilter from 'dist/jeelizFaceFilter';

function foo(){ 
     facefilter.init(...);
}
```

**Comment by xavierjs** [comment]
Hi,

I had released the lib on NPM a month ago but the current NPM version is not the latest one.

The main release is on github. I understand that doing what you say would be better for webpack developers for example but we want to keep it utterly framework agnostic. I use myself react/redux/webpack/npm and it is really a great working environment (https://jeeliz.com/sunglasses is made with that). We are a very small team (2 devs) so this github is the main release channel and I think I will remove the NPM distribution channel.

We also want to avoid a too strong react integration because the canvas holding the facefilter webgl context should not be detached from the DOM or recreated. This is what we do in our react/redux apps:

* in the main index.html we put the :  <script type="text/javascript" src="dist/jeelizFaceFilter.js"></script>
and the <canvas> element with a css attribute display:none . Because it is not in the react <app></app> it won't be unmounted.
* we initialize the API in the action creators by calling directly JEEFACEFILTERAPI.method(). In the react component we handle a <div> placeholder for the display. and then we match the <canvas> with the placeholder. If the placeholder is unmounted for example we hide the canvas. So the canvas is never detached.

**Comment by MateuszKicinski** [comment]
I understand your perspective, but from my point of view the API could be improved. I am not that experienced with JS but it's just seemed like something worth mentioning 😉 

PS I know I am complaining way too much, but overall I think you guys do a great job 😃

**Comment by xavierjs** [comment]
Thank you for your feedback, I keep this improvement in mind. We are currently working on other APIs and about boarding the solution through a fully open-source Nvidia Jetson setup... Many other stuffs are coming so!

**Comment by xavierjs** [comment]
Hi,

I have added an ES6 version of the API. It works with import and it should work with require too. It is in dist/jeelizFaceFilterES6.js. I have also add a small description in the readme : https://github.com/jeeliz/jeelizFaceFilter#using-es6

**Comment by xavierjs** [comment]
Hi,
I close the issue. Do not mind to re-open it if there is any problem with the ES6 version :)

**Comment by MateuszKicinski** [comment]
Thanks a lot!

**Comment by mschiano** [comment]
Is there a react example I could take a look at to see how it was implemented?
