### ISSUE TITLE
Portrait mode does not work ?

### ISSUE THREAD

**Issue by yuensunn** [jeeliz/jeelizFaceFilter#25]
**Describe the bug**
I have tried fiddling with `Optionnal init arguments` by adding`idealwidth` and `idealheight` in `videoSetting` but it does not seem to work.
```javascript
function init_faceFilter(videoSettings){

    JEEFACEFILTERAPI.init({
        canvasId: 'jeeFaceFilterCanvas',
        NNCpath: '../jeelizFaceFilter/dist/', // root of NNC.json file
        callbackReady: function(errCode, spec){
          if (errCode){
            console.log('AN ERROR HAPPENS. ERR =', errCode);
            return;
          }

          console.log('INFO : JEEFACEFILTERAPI IS READY');
          init_threeScene(spec);
        }, //end callbackReady()

        //called at each render iteration (drawing loop) :
        callbackTrack: function(detectState){
          onUpdate();
          THREE.JeelizHelper.render(detectState, THREECAMERA);
        }, //end callbackTrack()
        videoSetting:{'idealWidth':720,'idealHeight':1280}
        // videoSetting:{'idealWidth':1280,'idealHeight':720}
    
    }); //end JEEFACEFILTERAPI.init call

   
} // end main()
```
```html
<body onload="main()" style='color: white'>
        <!-- CANVAS BEHIND : VIDEO FACEFILTER ONLY -->
        <canvas  id='jeeFaceFilterCanvas' style="width :100vw; height: auto;"></canvas>


        <div id="reso" style ="font-size:2em; color: black"></div>

        <!-- CANVAS ABOVE : AR WITH THREE.JS -->
        <!-- <canvas width="600" height="600" id='threejsCanvas'></canvas> -->

        <button id="btn" style="position: relative; font-size:inherit;">Record</button>
    </body>
```
**Result**
Webcam texture seems to be in landscape mode still.
![alt text](https://i.imgur.com/4sVad65.jpg)

Webcam texture in landscape mode
![alt text](https://i.imgur.com/RnMaNwW.jpg)

**Comment by xavierjs** [comment]
Take a look here : https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints
idealWidth and ideal height are only suggested values : it impacts the resolution of the video. The resolution of a video is different from its displayed size. If the webcam cannot set to the given values it can return a video with a different resolution.

Set the displayed size by setting the width and height attributes of the canvas element. Then the video will be cropped to fit into the canvas. Give the idealWidth and height as if it was always lanscape values.

If you want to switch dynamically between landscape and portrait mode, you need to resize the canvas, call the JEEFACEFILTERAPI.resize() function to recompute the crop params of the video and to recompute your projection matrix.  You should take a look at the GLTF FULLSCREEN DEMO : https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/

**Comment by yuensunn** [comment]
Please correct me if I'm wrong. Based on what you have just said, it seems like there is no way to have a _true_ portrait video instead of cropping it from a landscape video? I have tried this [`sample demo`](https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/) on mobile, the video itself seems like it was cropped out of a landscape video (way too close up even with my arm extended at full length) [sample image](https://imgur.com/a/pUoDpGP)

**Comment by xavierjs** [comment]
If the camera is in landscape mode (a phone handled horizontally or a laptop), you will get a landscape video from getUserMedia API even if you request portrait ideal width and height.

Same for portrait mode : if your camera is in portrait mode, you will get a portrait video.

Then the video is cropped to fit the canvas the same way than CSS background: cover does : if the canvas is more landscape than the video we crop only top and bottom margins of the video, otherwise we crop only left and right margins.

But depending on the camera configuration sometimes the default zoom is too high. There is a draft API to give access to the camera intrinsic parameters but this is not available yet.

There are some informations about this issue here : https://github.com/jeeliz/jeelizFaceFilter/issues/22

The demo you have tried (https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/) is fullscreen. So it is in a very portrait mode (if we compute the canvas aspect ratio ac = canvasWidth/canvasHeight, ac is small).

I think the video from the webcam is less portrait (it depends a lot on the phone brand, the OS, the camera maker...). If we compute the video aspect ratio, av=videoWidth/videoHeight, we have av>ac .

So we need to crop the left and right margins quite a lot to display the video in fullscreen in order to not distort it or display blank space at the top/bottom.

So what I suggest is to not use a fullscreen canvas. With a square canvas for example we have ac=1 and the video should be less cropped (try the THREE.JS boilerplate demos for example).

**Comment by yuensunn** [comment]
I guess I will just use a square canvas until the new API releases. Thanks for the prompt feedback.

**Comment by xavierjs** [comment]
I close the issue. Do not mind to re-open it.

**Comment by ouzhou** [comment]
i tried your gltf_fullScreen demo,  it works
but the number of times it lost face is more bigger than rect canvas
any performance loss when fullscreen?

**Comment by ouzhou** [comment]
@xavierjs sorry i dont have any screenshot or any test code, i just  feel it become more worse than use rect canvas,  so if width !== height really cause performance loss?

**Comment by xavierjs** [comment]
In fullscreen mode, there are more pixels so it requires more computationnal power and it may be slower. It depends on your graphic hardware. The performance depends on the area of the canvas.
