### ISSUE TITLE
How to run jeeliz on a static image or custom video stream?

### ISSUE THREAD

**Issue by MateuszKicinski** [jeeliz/jeelizFaceFilter#26]
I noticed that using JEEFACEFILTER.init() only allows for detection of the face on the video stream accessed through getUserMedia(). As far as I understand there is no way to control the image/video which jeeliz analyses. I found out however that your sunglasses [example](https://jeeliz.com/sunglasses) allows to upload a custom picture. 

Is it possible to input custom image/video stream to jeelizFaceFilter ? If yes then how can I do it ? I've looked through the readme and tutorials but with no luck :(

**Comment by xavierjs** [comment]
This is possible: https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/
and the source code: https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/canvas2D/fromVideoFile

**Comment by MateuszKicinski** [comment]
Thanks!

**Comment by tarasprystavskyj** [comment]
This link is not working any more 
https://jeeliz.com/sunglasses/?sku=rayban_new_wayfarer_havane_marron_clair_degrade
as this server is not accessible 
https://fallbackglassesdb.jeeliz.com/

Is there any other accessible link with this example of using an image as a source intead of a webcam?

**Comment by xavierjs** [comment]
Hi,

There was a problem with the image rendering server.
I have restarted it and

**Comment by tarasprystavskyj** [comment]
Thank you for the quick turnaround. 
Where I can read about licensing of the module?

**Comment by xavierjs** [comment]
Hi,

Licensing of FaceFilter (this repo) is free since it is released under Apache2 licence.

However we provide developement services (integration/neural network improvement/specifics needs) using our libraries ( https://github.com/jeeliz ) to fit specific needs.

The sunglasses virtual tryon module used in https://jeeliz.com/sunglasses or https://github.com/jeeliz/jeelizGlassesVTOWidget is a specific case, because for this we provide the whole solution (hosting, glasses modelization, server side fallback rendering).
