### ISSUE TITLE
How to capture gif face replacement as video

### ISSUE THREAD

**Issue by vinothkrishnamoorthy** [jeeliz/jeelizFaceFilter#27]
Thanks for giving this awesome face filters.
I created a mobile app with gif face replacement but how to save the output?.
It has 2 canvas. I can able to record video from only 1 canvas at a time. 

Then gif file size is too high and quality is very less. Is it possible to do face replacement with any video formats such as webm, mp4 etc instead of gif?

**Comment by xavierjs** [comment]
Hi,

This problem is really a problem :(
If you save the output as a GIF, it would be very costly to compute the reduced color palette and a good dithering to avoid color border artifacts (https://en.wikipedia.org/wiki/Dither).
If you save the output as a video, there are 2 choices:
-either with canvas.captureStream(), it will be fast but it is not supported with Safari/IOS or Edge (https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream)
- either with Whammy.js, which encode the canvas in .webp. But it require that the browser implements the webp image encoding (ie you should be able to do var canvasDataURL=canvasDomElement.toDataURL('image/webp')). It is slower.

RecordRTC is a great wrapper around this: https://recordrtc.org/ but keep in mind It won't work on IOS... There is no way, either with Whammy or anvas.captureStream to get the canvas video stream (or I would be very interested to know how to do it!) 

You can do face replacement from a video format, since the input texture is given as a WebGL texture. You have to load your WebGL texture with the video.

**Comment by vinothkrishnamoorthy** [comment]
Thank you so much. 
I use captureStream(). Problem i faced is 
1. In facefilter demo new canvas element is created so there are 2 canvas element. I am unable to select both canvas in captureStream(). In output i get only my face and gif image is missing.

```

<div id="gifContainer">
            <canvas width="512" height="512" id="jeeFaceFilterCanvas" class="canvasDetected" style="top: 69px; left: 312px; width: 544px;"></canvas>
        <canvas width="450" height="206" class="gif" style="width: 766px; height: auto;"></canvas></div>
```

`document.querySelector('canvas');  // line from captureStream() selector`

if i select 1st or 2nd canvas by className. i get same output in both gif is missing.



I tried same with three.js demo files since it as only one canvas element it works well and video is generated. 

If possible create a demo for face replacement in video file.

**Comment by xavierjs** [comment]
You have to recode it in order to use only 1 canvas.
It requires a good level in WebGL and custom shader development.
You can take a look at the faceSwap demo, it uses only 1 canvas and the face insertion is the same (same color correction and same face cropping than the face replacement demo).
