### ISSUE TITLE
how to have a delay before filter is removed

### ISSUE THREAD

**Issue by Baraa-Baba** [jeeliz/jeelizFaceFilter#280]
what I mean by this if there was a face that was detected stops being detected the filter will wait like 5 seconds before it get removed and if it does find the face again before the 5 seconds it doesn't get removed 
thanks in advanced

**Comment by xavierjs** [comment]
Hi

1. Say hi (your mother should have taught you),
2. Say something understandable. Use punctuation to make separate sentences, start you sentences with an uppercase character,
3. Explain your issue, what you want to do, what did you try, and on what demo. Provide logs, videos, code... Like other people who do want to get help do,
4. Reread yourself and currently you should realize how bad is your posted issue.


If you don't spend time posting a real issue instead of nonsense rubbish, I won't spend time analyzing your issue, and I will also delete it because it has no interest to other users.

Also your issue seems not related to an issue in the library, but it seems related to a custom implementation issue. So its place should be in discussions, not in the issue part.

**Comment by Baraa-Baba** [comment]
Hey I am really sorry for wasting your time you were right I would try to make my point more clear  if had any other issues.
