### ISSUE TITLE
Error when I host it in server. Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded

### ISSUE THREAD

**Issue by VedantBH** [jeeliz/jeelizFaceFilter#30]
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xavierjs** [comment]
That's not a problem with facefilter, that's a problem with texture CORS. : Tainted canvases may not be loaded
you may use an image for a texture from another origin or protocol, so the canvas is tainted and some operation like GL.readpixel return this error.
It is explained here: https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

You should either use a proxy for your image to use them from the good origin, or use 2 canvas: 1 not tainted for facefilter and 1 tainted with THREE.JS like in this example: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/cube2cv


I close the issue because this is not a problem with facefilter
