### ISSUE TITLE
Frame is getting cut when I bring down in FaceDraw example.

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#33]
I want to place the frame below my face. I tried  CANVAS2D width and height, but no effect.
![facedraw](https://user-images.githubusercontent.com/19422397/44958004-4609c280-aef7-11e8-8b12-6ad2b3d3648d.PNG)

**Comment by xavierjs** [comment]
Of course, you draw the frame out of the canvas 2D...
Read the comments of https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/canvas2D/faceDraw/demo_faceDraw.js:

```
scale: [1,1.24], //scale of the 2D canvas along horizontal and vertical 2D axis
offsetYZ: [-0.1,-0.2], //offset of the 2D canvas along vertical and depth 3D axis
```

You have to play with that to move or to scale the canvas2D
width and height of the canvas2D are its resolution, it has nothing to do with the displayed size of the canvas2D because the displayed size is controlled by the face detection.
