### ISSUE TITLE
Color facial features, like eyes, lips, cheek bones

### ISSUE THREAD

**Issue by nitish24p** [jeeliz/jeelizFaceFilter#36]
Firstly, this is a fantastic library.. really well implemented and documented. Although i did get stuck in the following places.
1. Using the `faceLowPoly.json` can i highlight the meshlines in the video, currently when i try to do it. I get the entire mesh as 1 solid object.

2. Further extension of the one above, can i color certain triangles(facial markers) like lips eyes with colors? Basically detect the lips and then color them..

If so how do i go about doing this

**Comment by xavierjs** [comment]
Hi,

1. You need to use another mesh, a textured mesh or to split the geometry into several mesh if you want to use the parts separately.

2. Then you won't have a good rendering because to outline the lips we should be able to get the coords of the lip points and this is not possible:

> Currently the detection is global, without going through key points like the methods of Active Shape Model of BRFV4 for example (https://github.com/Tastenkunst/brfv4_javascript_examples).
> So we do not have the opportunity to finely cut the lips eg.
> However I think it would be possible to learn the position of key points. Instead of the network outputting the 3D transformation of the head + 2D framing it would give the position of the key points.
> This is not yet in our pipeline (we switch a little presta mode with the integration of virtual fitting of glasses and facial filters for the next few months) but it could be

Before doing 3d programming with this library, I suggest you to learn the basics of 3D programming and THREE.JS : mesh parsing, texturing, positioning, projection... http://www.webglacademy.com can be a good point to start.

**Comment by xavierjs** [comment]
I close the issue because there is nothing new.
We are working on a landmark based version of the library, FaceFilterLM, but there is still a lot of work to do :)
