### ISSUE TITLE
Video does not play when opening a new window through other page

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#46]
First, thanks for this good library.

**Describe the bug**
demos/threejs/miel_pops/index.html

I made a new page. Then I created an action to go to the video page. However, I found that the video page does not play or play when you open a new window

**To Reproduce**
1. Create page 'test.html'
````javascript
<html>
    <head>
        <script>
        </script>
    </head>
    <body>
        <button style='font-size:10vw'; onclick='window.open("demos/threejs/miel_pops/index.html")'>new window</button>
    </body>
</html>
````
2. Click button 'new window'
3. Go to 'demos/threejs/miel_pops/index.html'
4. Camera permission check -> yes
4. playing video
5. return page 'test.html'
6. 2->3->4-> can't playing video.(return errCode = 'WEBCAM_UNAVAILABLE')

attempt: 1~6
First attempt = playing video
Second attempt = can't playing video
Thrid attempt = playing video
Fourth attempt = can't playing video

I tried other cases.

1.  I tried with  'location.href' instead of 'window.open'. it's always playing video. I think 
it's a problem with safari and 'window.open'.

2. When the video is played back, the video plays even if the page is refreshed. However, when the video is not playing, the video does not play when the page is refreshed.

**Expected behavior**
Everyday can playing video.

**Desktop (please complete the following information):**
Does not happen with Desktop
 - OS: Mac os
 - Browser: chrome 69.0.3497.100, safari  12

**Smartphone (please complete the following information):**
_Occurs only on Mobile Safari(Does not happen with developer mobile tools)_
 - Device: iPhone6s, iPhoneX
 - OS: iOS 12.0
 - Browser : safari 12

**Additional context**
I was trying to get a point of getting the video rights. but it's in jeelizFaceFilterES6. I'm sorry that the situation is complicated.

**Comment by whilemouse** [comment]
I tried jeeliz VTO.

1. Safari in iPhone
2. Go to https://jeeliz.com/
3. Click link 'Try our demo application'
![image](https://user-images.githubusercontent.com/16111790/47077152-48bc3f00-d23b-11e8-87a9-aadab63db1c7.png)
4. Open new tab 'https://jeeliz.com/sunglasses/'
5. Click 'Start the experience'
6. Alternating between video playback and non-video playback.

![img_dafcd05d1064-1](https://user-images.githubusercontent.com/16111790/47077760-a1400c00-d23c-11e8-8315-a442e5304ed6.jpeg)

**Comment by xavierjs** [comment]
Hi @whilemouse 

Thank you for this detailled bug report.

I have not deployed your fix yet on the VTO widget an app (https://github.com/jeeliz/jeelizFaceFilter/issues/45)
I am currently finishing to train a better neural net, I will rebuild the app with the fix and the new neural net model in a cuple of days.

But the WEBCAM_UNAVAILABLE error is also often triggered when another application is using the webcam (Skype, Google hangout, another browser windows or tab).

I have not my Ipad with me today and it is not yet updated to iOS12 but I will test for sure by the end of the week.

I think you should avoid `window.open()`. Popup killers hate this, and the behavior can be different from one browser to another. I prefer to use `<a onclick="launch_stuff()" href='test.html' target='_blank'>CLICK HERE</a>` . Since it opens a new window/tab and execute launch_stuffs() after a user action (click), we are pretty sure we won't be bothered by browser security protections.

best,
Xavier

**Comment by xavierjs** [comment]
Hi,

I have updated the VTO application, it should work now.
You still have to try it in a private browser window since there may be cache problem (it uses service workers and put a lot of stuffs into the browser cache).
The direct link to the app is here: https://jeeliz.com/sunglasses/

Best,
Xavier

**Comment by whilemouse** [comment]
Hi, @xavierjs 

Thank you for always fast and accurate solution.
Works exactly in VTO.

I thought this was a problem with webRTC and request it to webRTC. And I was looking at the webRTC code.
[request link](https://github.com/webrtc/samples/issues/1140)

If you don't mind, can you tell me how you solved this problem?

**Comment by xavierjs** [comment]
That was exactly this problem you mentionned: https://github.com/webrtc/samples/issues/1140
The WebRTC helper included in the VTO lib is this one: https://github.com/jeeliz/jeelizAR/blob/master/helpers/JeelizMediaStreamAPIHelper.js
I have included your fixe into it (line 339)
On the VTO widget and FaceFilter this helper is packed and included into the lib.
I dit a helper to wrap WebRTC because there are many workarounds, especially with mediaconstraints...

**Comment by whilemouse** [comment]
Thanks. @xavierjs 
I always write well. I'll try to contribute.

**Comment by xavierjs** [comment]
It seems to be resolved :)

**Comment by xavierjs** [comment]
Ops I did a mistake by closing this issue.

**Comment by xavierjs** [comment]
Yes this is true: 

The modification at line 339 of:
https://github.com/jeeliz/jeelizAR/blob/master/helpers/JeelizMediaStreamAPIHelper.js

only applies to:
https://github.com/jeeliz/jeelizFaceFilter/issues/45

For this issue, I think this is a Chrome bug unfortunately :(

Best,
Xavier

**Comment by whilemouse** [comment]
Thanks. :)

Best,
whilemouse
