### ISSUE TITLE
iOS 12 WebGL2.0 enabled, GL_INCOMPATIBLE error

### ISSUE THREAD

**Issue by star277hk** [jeeliz/jeelizFaceFilter#47]
While using iOS 12 and enabled WebGL2.0 in advanced setting, it goes to GL_INCOMPATIBLE error.

**Comment by xavierjs** [comment]
Thanx for this feedback, I am working to solve the problem.

**Comment by xavierjs** [comment]
The implementation of WebGL2 on iOS is very shitty and I hope they will improve it soon. Many  Khronos Group WebGL2 conformance tests on framebuffers/renderbuffers fail (https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html?version=2.0.0).

The problem comes from that there is no way to do render to texture using FLOAT or HALF_FLOAT precision :(.
This is a regression compared to WebGL1.
So I cannot run any neural network in these conditions... 8 bits precision is not enough... 

As WebGL2 is not enabled by default, I won't add a workaround with a WebGL2 blacklist to force the use of WebGL1 for IOS12 devices.

But if the bug is still here when WebGL2 will be enabled by default, I will do something.

**Comment by star277hk** [comment]
Thanks for the very quick reply. Hope apple will work on their better safari in next os version. Thanks again !

**Comment by xavierjs** [comment]
I re-open the issue in order to think to check WebGL2 again on IOS12 as soon as it will be enabled by default.

**Comment by xavierjs** [comment]
As WebGL2 is enabled by default since the last IOS update (to 12.1) and it is still badly implemented, I have just committed a workaround.
If IOS12 is detected, WebGL1 will be used instead of WebGL1.
I close the issue.
