### ISSUE TITLE
Changing Filter Source

### ISSUE THREAD

**Issue by andres934** [jeeliz/jeelizFaceFilter#48]
**Describe the bug**
The actual behavior of the filter is using the user camera, this time i already have a video to apply the filter to, but can't manage to change the library source to take that video instead of the camera, i tried with the dog face filter demo and the babylon cube, but no luck, where can i change that source on those demos?

**To Reproduce**
This is actually not a error/bug

**Expected behavior**
what i'm expected to happen is the dog face filter or the babylon cube working using an actual video tag as source, i can send that video to a canvas if is necessary

**Screenshots**

**Desktop (please complete the following information):**
-Chrome, Safari, Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andres934** [comment]
Just saw a couple of similar questions over here where you suggest to use Canvas2D demo, i just add it but have this issue on js console: 
![image](https://user-images.githubusercontent.com/2755306/47355848-c57b6d00-d6c2-11e8-9b4f-627fff42c606.png)

**Comment by xavierjs** [comment]
Hi,

The first error is normal, it is when the lib tests the real WebGL capabilities are they are handled.
For the second it may be a hosting problem. Do you use a HTTPS server ?
This demo should work:
https://jeeliz.com/demos/faceFilter/demos/canvas2D/fromVideoFile/

If you want to change the source of the video, all is explained in the readme here:
https://github.com/jeeliz/jeelizFaceFilter#optionnal-init-arguments
you have to play with the videoSettings init arg.

* Either you give a custom <video> element by affecting videoElement
* Either, if you have 2 webcams and you want to use a specific one, you can specify the deviceId or change the facingMode.
The deviceId can be found using MediaSource API (https://developer.mozilla.org/en-US/docs/Web/API/MediaSource).

Since this is not an issue directly linked with the library, I won't publish a detailed solution here, but if you are interested by a development service to solve you problem, you can contact us to get a proposal.

Best,
Xavier

**Comment by andres934** [comment]
the demo is actually working! as the matter of fact, that error was on Safari, because i load it on Chrome and works fine, but it kind of zoom a little bit the actual video, how can i handle that zoom? i just want to use the exact same video resolution, i thank you and appreciate the time you took to answer my question

**Comment by xavierjs** [comment]
MediaStream API is awful, there are tons of workarounds to add in order to make it work almost everywhere... That's why the video acquisition have been included into the library.
Otherwise the original video helper is here: https://github.com/jeeliz/jeelizAR/blob/master/helpers/JeelizMediaStreamAPIHelper.js

In this helper we try to get the video stream with the given constraints, then if we cannot we downgrade the constraints and so on... We do this operation automatically with a timeout because sometimes there are deadends (the error callback is not even called).

I found a weird error yesterday. Chrome takes a lot of time (around 500ms) to get the 4:3 video and my timeout was too short (200ms), so it gives up with the 4:3 video constraints and try with other video constraints, very close but where the video is in 16:9 format. So it has to be more cropped and it will appear larger. I will deploy the fix very soon :)

**Comment by andres934** [comment]
oh great! i will check out that helper, thank you a lot, that fix will help a lot! hopefully that will fix the issue on Chrome

**Comment by andres934** [comment]
Just tried what you said about changing the video source and console showed me this:
![image](https://user-images.githubusercontent.com/2755306/47372260-b4922200-d6e9-11e8-8517-7805cc6838b7.png)
![image](https://user-images.githubusercontent.com/2755306/47372273-bf4cb700-d6e9-11e8-8f45-75b28b1da01a.png)

i Just set my video element as videoSettings, that's all

**Comment by xavierjs** [comment]
the error you show is with THREE.JS, not with the video element

**Comment by andres934** [comment]
yes, exactly, i don't know what could i do wrong

**Comment by xavierjs** [comment]
I can provide a dev service for that, but I do not work for free :) (except when fixing bugs on the demos).

**Comment by andres934** [comment]
of course, i understand, what are the dev services costs?

**Comment by xavierjs** [comment]
Can you contact me, my email is xavier __at__ jeeliz.com I will send you my rate. 

Thank you
