### ISSUE TITLE
using existing video element

### ISSUE THREAD

**Issue by jensmeggers** [jeeliz/jeelizFaceFilter#50]
I'm trying to get the face detection to run with an exiting video element that gets video from the local webcam. I don't see an error but for some reason it doesn't detect anything. I'm using Chrome 70 on Windows. 
(If I remove the videoSettings then it starts working right away)

[example.zip](https://github.com/jeeliz/jeelizFaceFilter/files/2527334/example.zip)

**Comment by xavierjs** [comment]
Hi,

Your call to WebRTC is deprectated I think. It lacks polyfills and the way you affect the video feed to the <video> element (video.src=createObjectUrl(...)) is obsolete (now it uses .srcObject).
The polyfill included in the Jeeliz FaceFilter library is the same than  https://github.com/jeeliz/jeelizAR/blob/master/helpers/JeelizMediaStreamAPIHelper.js

Maybe you also ask for invalid mediaconstraints. Before providing the <video> element to FaceFilter library you should append it to the DOM in order to inspect it. Futhermore it is mandatory for Apple WebRTC implementation (if a <video> element is not in the DOM it won't play so you still have to append it and to play with the CSS to hide it).

I don't inspect these kinds of bugs here since it does not come from the FaceFilter library webRTC implementation. The WebRTC invocation has been included into the main library file in order to overcome all mediaconstraints and compatibility problems. If you don't use it, I strongly advise to not use directly WebRTC because there are many polyfills and workarounds to make it work everywhere :(.

**Comment by cwoo3511** [comment]
Hi,

First thank you this is a great code.
Can I apply this example to a video chat using webrtc?
Or can you give me some advice on making a video chat?

Please.
