### ISSUE TITLE
Destroy method for SPA web sites

### ISSUE THREAD

**Issue by Dok11** [jeeliz/jeelizFaceFilter#57]
**Describe the solution you'd like**
Method for destroy lib requestAnimationFrame and future reinitialize lib.

**Additional context**
After closing modal window the canvas destroy, but when I open modal window again and run `JEEFACEFILTERAPI.init` the jeelizFaceFilter throw error

**Comment by xavierjs** [comment]
Hi,

JEEFACEFILTERAPI.init is quite heavy because It has to get the neural network model (NNC.json) which is quite heavy, and to instantiate a lot of stuffs.

So for optimization purpose, I strongly advice to initialize it once and for all.
* When you do not use it, you call JEEFACEFILTERAPI.toggle_pause(...) to stop/restart the rendering loop
* You unmount the canvas element from the DOM when the popup is closed, and you mount it to the new popup when it is open.

I agree that it is not very compliant with some paradigm like React/redux applications.
But with react, using the standard component cycle handlers (ComponentDidMount, componentShouldUpdate etc...) it is very doable.
