### ISSUE TITLE
Can you provide example with gltf?

### ISSUE THREAD

**Issue by Laoutari** [jeeliz/jeelizFaceFilter#58]
Hi,

I like your project. Thank you. I've tried to examples and tried to change the models. The version of blender I've downloaded doesn't support the export to three.js. Adding that plugin isn't possible any more. They dropped support for three.js. I could use glTF 2.0 instead but couldn't get that to work. Would you it be possible to provide an example with glTF 2.0?

I tried...

    var loader = new THREE.GLTFLoader(loadingManager);

    // Optional: Provide a DRACOLoader instance to decode compressed mesh data
    //THREE.DRACOLoader.setDecoderPath( './nodecoder' );
    //loader.setDRACOLoader( new THREE.DRACOLoader() );

    // Load a glTF resource
    loader.load(
        // resource URL
        './mymodel.glft',
        // called when the resource is loaded
        function ( gltf ) {

            scene.add( gltf.scene );

            gltf.animations; // Array<THREE.AnimationClip>
            gltf.scene; // THREE.Scene
            gltf.scenes; // Array<THREE.Scene>
            gltf.cameras; // Array<THREE.Camera>
            gltf.asset; // Object

        },
        // called while loading is progressing
        function ( xhr ) {

            console.log( ( xhr.loaded / xhr.total * 100 ) + '% loaded' );

        },
        // called when loading has errors
        function ( error ) {

            console.log( 'An error happened' );

        }
    );    

Doesn't seem to work. I included the below in the index.html.
        <script type="text/javascript" src="../../../libs/threejs/v97/GLTFLoader.js"></script>

In blender I exported a curve as gltf 2.0, export all layers, convert z up to y up, export all texture coordinate, normals, tangents, colors.

Any ideas?

tx,

Laoutari

**Comment by xavierjs** [comment]
Hi,

This has nothing to do with FaceFilter library, that's why I close the issue.

As I have written here: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs
the Blender THREE.JS exporter is no longer included into THREE.JS, that's why it is included into this repository. Of course, because it is no longer maintained, the compatibility problem with a next Blender version is unavoidable.

If you want to import GLTF2.0 meshes with three.js, you can ask here: https://github.com/mrdoob/three.js/ 

You can also try with various other THREE.JS format which have loaders (OBJ, COLLADA, FBX, ...)

Best,
Xavier
