### ISSUE TITLE
Can i please understand the differences between some of the demos

### ISSUE THREAD

**Issue by alexbudin** [jeeliz/jeelizFaceFilter#62]
Can i please understand the differences between the bellow boilerplates in terms of performance on mobile browser support, advantages of using one over another and face tracking accuracy for each one.

This would be immensely helpful, not only for me but for everyone wanting to use this for bigger projects but cant have all the know how to differentiate them all and ick the right one for their project. i hope this makes sense.

Also on No. 3 (Boilerplate with 2 canvas: 1 for FaceFilter and 1 for THREE.JS), why are there 2 canvases being used and whats the difference between this one and No. 1.

1. Boilerplate (displays a cube on the user's head)
2. Boilerplate with ES6
3. Boilerplate with 2 canvas: 1 for FaceFilter and 1 for THREE.JS
4. Boilerplate using dist/NNClight.json as neural net
5. Boilerplate using dist/NNCwideAngles.json as neural net
6. Boilerplate without JeelizThreeHelper
8. GLTF fullscreen demo with HD video

Thank you so much.

**Comment by xavierjs** [comment]
Hi,

Boilerplate (displays a cube on the user's head)
-> old boilerplate, it will be removed from next versions

Boilerplate with ES6
-> use only if you use ES6. I do not advise

Boilerplate with 2 canvas: 1 for FaceFilter and 1 for THREE.JS
-> not the best

Boilerplate without JeelizThreeHelper
-> you should use this one

Boilerplate using dist/NNClight.json as neural net
-> boilerplate with another neural net. will be removed soon ( not the neural net, only the boiletplate)

Boilerplate using dist/NNCwideAngles.json as neural net


GLTF fullscreen demo with HD vide

**Comment by alexbudin** [comment]
wow Xavier, thats awesome! Thank you so much. 

I have 3 more follow up questions - quick ones i hope, all about performance:

Whats the difference between the below 2  boiler plates ? in terms of performance?
Boilerplate using dist/NNClight.json as neural net
Boilerplate using dist/NNCwideAngles.json as neural net


Whats the difference in performance between the below 2?
Boilerplate without JeelizThreeHelper
Boilerplate using dist/NNCwideAngles.json as neural net


And the last question:

Is the GLTF fullscreen demo with HD video good in performace, compared with the **Boilerplate without JeelizThreeHelper** or the **Boilerplate using dist/NNCwideAngles.json**

Thank you so much.


Alex

**Comment by xavierjs** [comment]
I have improved a bit the descrption of these boilerplates in the readme, and I have deleted the deprecated boilerplate and replaced it by cubeWithBoilerPlate.
NNClight.json and NNCwideAngles.json are 2 différent neural nets.
There are short details about them here: https://github.com/jeeliz/jeelizFaceFilter#changing-the-neural-network

NNClight is faster and lighter but it can be hard to stabilize than heavier neural nets. It can be nice for mobile applications.
NNCwideAngles.json is heavier and smaller, and have been trained with larger angles.
There is always a trade off between training a small, fast and light neural net which output will be too noisy and which will limited in term of learning features or training a heavier neural net, which will be slower but more accurate. That's why I put several neural nets. You can switch between them easily. I made copies of the boilerplate with different neural networks in order to be able to quickly test them.

You should not use "Boilerplate without JeelizThreeHelper", I have just removed it from the repository, it is deprecated. In the THREE.JS helper I have included important corrections from https://github.com/jeeliz/jeelizFaceFilter/issues/42 or https://github.com/jeeliz/jeelizFaceFilter/issues/56 so you will get better results using the helper.

The GLTF fullscreen demo ask for a better video resolution, and there are more pixels to compute so it may be slower. it really depends on the configuration. The detection is adaptative up to some point: if your device is powerful, there are more detections per seconds, so the tracking is faster and more accurate. Currently the cheaper devices to run the demos smoothly is a Samsung Galaxy A5 or a Motorolla Xplay. It will work on lower devices but it may be slow.
Of course on IphoneX, Ipad pro or Samsung galaxy S7 S8 it should run perfectly.

**Comment by alexbudin** [comment]
These are some great explanations, hopefully people find these, or maybe we can have some of this in the readme.

Quick question:

**Boilerplate (displays a cube on the user's head)** how does it detect the face and keep track of it? Im assuming its not using a neural network as the other examples, thus is faster? Im sorry if this might seem as a very silly question.

**Comment by alexbudin** [comment]
Nevermind my last question, it was stupid :)
