### ISSUE TITLE
Placing in 3D

### ISSUE THREAD

**Issue by vbh25** [jeeliz/jeelizFaceFilter#68]
Trying to place earrings using luffy hat 1 example.
A portion of it comes on cheeks. How to place it behind the cheeks.
![pic](https://user-images.githubusercontent.com/19422397/48941953-8ea7a980-ef43-11e8-9c7c-e8c1a2510fd5.PNG)

**Comment by xavierjs** [comment]
Hi,

The detection is centered on the point between the 2 eyes.
So this lib is good to do glasses virtual try-on, but more you get further from the central point, more you will have errors depending on the user's head particular shape, detection noise...

I think it may be hard to get a good result for earings...
If you want to mask the part behind the head you need to do this in three.js, use a half-transparent texture and a 3D face occluder mesh like in the demo: https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/VTO

**Comment by vbh25** [comment]
Okay thanks

**Comment by vbh25** [comment]
Do you suggest any tutorials to understand why occluder must be used & how it places frame, lenses & glass at the right position on face ?

**Comment by xavierjs** [comment]
Hi,
First I think you should well understand vanilla WebGL workflow then THREE.JS.
You will always be blocked in THREE.JS if you did not start with basics of 3D programming (maths, movement matrix, projection matrix) and OpenGL.
For this fortunately there are good resources online. http://webglacademy.com , http://learningwebgl.com/ (I started with that), https://webglfundamentals.org/.
It is always good to do several tutorials instead of one, because you will understand much more things when it is explained differently.

If you just want a demo then your problem is really close to the glasses VTO demo (https://github.com/jeeliz/jeelizFaceFilter/tree/master/demos/threejs/VTO).
to position stuffs in three.js the best way is to make then global with `window.debugYourMesh=<yourInstanceOfThreeMesh>` then lanch in the javascript console `debugYourMesh.position.set(x,y,z)` until you find the good position. same for scale or rotation.

**Comment by vbh25** [comment]
Okay, Thanks a lot.
