### ISSUE TITLE
Lag on placement when moving

### ISSUE THREAD

**Issue by andrewdeutsch** [jeeliz/jeelizFaceFilter#9]
Hey again,
I'm curious is there's a way to modify the easing on elements when you move using the Football fan demo. I didn't see any speed variables and thought it might be a three.js value. As it currently works, it seems the mesh takes a second to catch up with me.

Also, when I turn my head left or right, the position of the elements scales in a strange way. To the left, everything gets smaller, to the right, everything gets bigger.

Thanks again!

**Comment by xavierjs** [comment]
Hi Andrew,

You can try to change the  pivotOffsetYZ: [-0.1,0.5] in the SETTINGS. The value along the Z axis is too large, I think 0.2 should fit better.

Then the demo uses a MeshStandardMaterial, it is a PBR material and it is slower to render than a phong material. Since lighting do not matter a log I would suggest to use a MeshBasicMaterial or a MeshLambertMaterial. 

Then its alphaMap is 1024x1024 pixels and it could be reduced to 512x512 pixels or even to 256x256 pixels.
You should also try without lighting indeed the spotlight is useless.

**Comment by bjlaa** [comment]
Hi Andrew,

I added the optimizations mentioned by Xavier to the football_makeup demo. I haven't been able to reproduce the strange scaling you were talking about but I added a debug color parameter to the face mesh material to see better how the mesh reacts to the user turning his head left and right and how the pivotOffsetYZ setting affects it.

<img width="734" alt="capture d ecran 2018-05-21 a 09 34 47" src="https://user-images.githubusercontent.com/12382534/40295830-124f52d4-5cdb-11e8-8e52-a8df4192a616.png">

**Comment by andrewdeutsch** [comment]
Thanks for that, @bjlaa. I actually moved my assets to the hat demo and it's working a bit better.

**Comment by andrewdeutsch** [comment]
Hi Xavier,
I’m looking forward to Wednesday!
I’m curious-does Jeeliz have a plan to build a rear facing camera demo?
This company offers one in the browser, I can’t wrap my head around how
they’re doing it...
https://www.vertebrae.com/mobile-web-ar-advertising/

Thanks,
Andrew
-- 
917.482.1004   https://www.somewonderstuff.com
